# Generated by Django 2.2.28 on 2023-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bittest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bittest',
            name='fitest',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
