# Generated by Django 2.2.28 on 2023-05-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bittest_fitest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zak12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert', models.GenericIPAddressField()),
                ('vcwrr', models.SlugField(blank=True, null=True)),
                ('zabtr', models.DateTimeField(blank=True, null=True)),
                ('lopi', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('xcopu', models.ManyToManyField(blank=True, related_name='zak12_xcopu', to='home.Bittest')),
            ],
        ),
    ]
