# Generated by Django 2.2.28 on 2023-05-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_zak12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zak12',
            name='zabtr',
        ),
    ]
