# Generated by Django 2.2.28 on 2023-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_zak12_zabtr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xewrwt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmjui', models.CharField(max_length=256)),
                ('ncery', models.DurationField(blank=True, null=True)),
                ('qasdd', models.UUIDField(blank=True, null=True)),
                ('ertfd', models.FloatField(blank=True, null=True)),
                ('iuyt', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
