# Generated by Django 2.2.28 on 2023-05-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_xewrwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xewrwt',
            name='iuyt',
        ),
    ]
