# Generated by Django 2.2.28 on 2023-05-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_xewrwt_iuyt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xewrwt',
            name='ertfd',
        ),
        migrations.RemoveField(
            model_name='xewrwt',
            name='qasdd',
        ),
    ]
