# Generated by Django 2.2.28 on 2023-05-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_vyui'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zak12',
        ),
    ]
